camera:
    # All the vectors are [x, y, z] coordinates
    position:   [0, 1, -20]  # The position of the camera
    lookAt:     [2, 0, 0]  # The point to look at
    upVec:      [-0.2, 1, 0]  # The "up" direction vector which determines the
                              # orientation of the camera
    fov:        1.5           # The tangent of the view angle

scene:
    resolution: [1920, 1080]   # [width, height] of the image
    bloomStrength: 0.15 # The strength (weight) of the bloom effect. Setting this to
                        # 0 disables it entirely
    bloomDivider: 25  # A number x such that r = image width / x is the bloom radius

    starIntensity: 0.4   # The intensity (0 = black, 1 = white) of the stars
    starSaturation: 1.5  # The color saturation of the stars

    diskOpacity: 0.2   # Opacity of the accretion disk (0 = fully transparent,
                       # 1 = fully opaque)
    diskInner:  2      # The inner radius of the accretion disk
    diskOuter: 12      # The outer radius of the accretion disk
    diskColor: [180, 0.1, 0.9]  # The colour of the accretion disk in the HSI color space.
                                # H: 0..360, S: 0..1, I: 0..1

    supersampling: false  # Set this to true to enable smoothing by supersampling
                          # a 4x sized image
    stepSize: 0.3  # The size of the timestep in the simulation. Usually this value
                   # should be fine.
