resolver: lts-13.25
extra-deps:
- github: 'AccelerateHS/accelerate'
  commit: 4cf97cd4f3844187e6eb232d118c680123302267
- github: 'AccelerateHS/accelerate-llvm'
  commit: e0f1a7676d160168440ed8338f2054014976646b
  subdirs:
  - accelerate-llvm
  - accelerate-llvm-native
- github: 'AccelerateHS/accelerate-io'
  commit: b909e3e225fff5f6eadeddc8668ef65677b19f9f
  subdirs:
  - accelerate-io
  - accelerate-io-JuicyPixels
  - accelerate-io-vector
- github: 'tmcdonell/colour-accelerate'
  commit: edc575cc6a810f5cce8d4b4423ef3968f30a93a3
- github: 'ekmett/linear-accelerate'
  commit: d7ca0750520aa12bbd4ce07d4119f47803eef4a3
- llvm-hs-8.0.0
- llvm-hs-pure-8.0.0
flags:
  llvm-hs:
    shared-llvm: true
extra-package-dbs: []
packages:
- '.'
